// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIconBell: typeof import('@element-plus/icons-vue')['Bell']
    ElIconClose: typeof import('@element-plus/icons-vue')['Close']
    ElIconDArrowLeft: typeof import('@element-plus/icons-vue')['DArrowLeft']
    ElIconDArrowRight: typeof import('@element-plus/icons-vue')['DArrowRight']
    ElIconDocumentDelete: typeof import('@element-plus/icons-vue')['DocumentDelete']
    ElIconDownload: typeof import('@element-plus/icons-vue')['Download']
    ElIconExpand: typeof import('@element-plus/icons-vue')['Expand']
    ElIconFold: typeof import('@element-plus/icons-vue')['Fold']
    ElIconHide: typeof import('@element-plus/icons-vue')['Hide']
    ElIconMenu: typeof import('@element-plus/icons-vue')['Menu']
    ElIconMinus: typeof import('@element-plus/icons-vue')['Minus']
    ElIconRefresh: typeof import('@element-plus/icons-vue')['Refresh']
    ElIconView: typeof import('@element-plus/icons-vue')['View']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    MeComponent: typeof import('./components/meComponent.vue')['default']
    MeDarkSwitch: typeof import('./components/meDarkSwitch.vue')['default']
    MeKeepAlive: typeof import('./components/meKeepAlive/index.vue')['default']
    MeLocaleSelect: typeof import('./components/meLocaleSelect.vue')['default']
    MeSizeSelect: typeof import('./components/meSizeSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
